language: node_js
node_js:
  - stable

script:
  - yarn test
  - yarn build

branches:
  only:
    - master
    - next
    - /^release\/.*$/

before_deploy:
  - cd lib

deploy:
  skip_cleanup: true
  provider: npm
  email: hey@nielsbik.nl
  api_key: $NPM_TOKEN
  on:
    branch: master

notifications:
  email:
    on_success: change
    on_failure: change